---
title: "hwrk9 - Beimnet Taye"
output: pdf_document
date: "2023-03-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(medicaldata)
library(simcausal)


```

## P1

### 1.
```{r}
scurvy = medicaldata::scurvy %>%
mutate(
# collapse treatment into two groups
citrus = forcats::fct_collapse(
treatment,
"TRUE" = c("cider", "dilute_sulfuric_acid", "vinegar", "citrus"),
"FALSE" = c("sea_water", "purgative_mixture"),
) %>%
as.logical(),
# turn outcome into a numeric measure
gum_rot = gum_rot_d6 %>%
stringr::str_sub(1, 1) %>%
as.numeric()
) %>%
select(citrus, gum_rot)

naive <- scurvy %>% 
  group_by(citrus) %>% 
  summarize(mean = mean(gum_rot))

naive_ATE <- naive[2,2] - naive[1,2]

naive
naive_ATE


```

### 2.
```{r}
scurvy_counter <- scurvy %>% 
  mutate(gum_rot_yes_citrus = ifelse(citrus == TRUE, gum_rot, NA),
         gum_rot_no_citrus = ifelse(citrus == FALSE, gum_rot, NA)
         )

scurvy_counter

```

### 3.
```{r}
citrus_bad <- scurvy_counter %>% 
  mutate(gum_rot_yes_citrus = ifelse(citrus == FALSE, 3, gum_rot),
         gum_rot_no_citrus = ifelse(citrus == TRUE, 0, gum_rot)) 

citrus_bad %$% {
  mean(gum_rot_yes_citrus) - mean(gum_rot_no_citrus)
} 

citrus_bad
```

### 4.
```{r}
citrus_good <- scurvy_counter %>% 
  mutate(gum_rot_yes_citrus = ifelse(citrus == FALSE, 0, gum_rot),
         gum_rot_no_citrus = ifelse(citrus == TRUE, 3, gum_rot)) 

citrus_good %$% {
  mean(gum_rot_yes_citrus) - mean(gum_rot_no_citrus)
} 

citrus_good
```

### 5.
```{r}
citrus_equal <- scurvy_counter %>% 
  mutate(gum_rot_yes_citrus = ifelse(citrus == FALSE,0, gum_rot),
         gum_rot_no_citrus = ifelse(citrus == TRUE, 2.125, gum_rot)) 

citrus_equal %$% {
  mean(gum_rot_yes_citrus) - mean(gum_rot_no_citrus)
} 

citrus_equal
```

## P2

### 1.
```{r}
causal_dgp_1 = function(n=100) {
tibble(
X = runif(n,-1,1), # a covariate
A = rbern(n, prob=1/2),
Y0 = rnorm(n, mean=sin(pi*X)+1/3),
Y1 = rnorm(n, mean=cos(pi*X)),
)
}
observable_dgp_1 = function(n=100) {
causal_dgp_1(n) %>%
mutate(Y = ifelse(A, Y1, Y0)) %>%
select(-Y0, Y1)
}

naive_ate_estimator = function(data) {
data %$%
{ mean(Y[A==1]) - mean(Y[A==0]) }
}
```

```{r}
true_ate <- causal_dgp_1(1000000) %$% {
  mean(Y1) - mean(Y0)
} 
true_ate
```

### 2.
```{r}
bias <- function(data, estimator, rep = 10, n = 100){
  
}
```

